// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum AdapterState { on, off, unavailable, unauthorized }

enum PermissionState { granted, denied, permanentlyDenied }

/// La caratteristica da cui è arrivata una trama.
enum Characteristic { response, telemetry }

/// Una trama già verificata dal C: tipo, sequenza e contenuto. CRC e versione
/// non attraversano il canale.
class WireFrame {
  WireFrame({required this.type, required this.seq, required this.payload});

  int type;

  int seq;

  Uint8List payload;

  List<Object?> _toList() {
    return <Object?>[type, seq, payload];
  }

  Object encode() {
    return _toList();
  }

  static WireFrame decode(Object result) {
    result as List<Object?>;
    return WireFrame(
      type: result[0]! as int,
      seq: result[1]! as int,
      payload: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WireFrame || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(seq, other.seq) &&
        _deepEquals(payload, other.payload);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WireFrame(type: $type, seq: $seq, payload: $payload)';
  }
}

sealed class BleEvent {}

class ScanResultEvent extends BleEvent {
  ScanResultEvent({required this.deviceId, this.name, required this.rssi});

  String deviceId;

  String? name;

  int rssi;

  List<Object?> _toList() {
    return <Object?>[deviceId, name, rssi];
  }

  Object encode() {
    return _toList();
  }

  static ScanResultEvent decode(Object result) {
    result as List<Object?>;
    return ScanResultEvent(
      deviceId: result[0]! as String,
      name: result[1] as String?,
      rssi: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanResultEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) &&
        _deepEquals(name, other.name) &&
        _deepEquals(rssi, other.rssi);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ScanResultEvent(deviceId: $deviceId, name: $name, rssi: $rssi)';
  }
}

class ConnectionEvent extends BleEvent {
  ConnectionEvent({
    required this.deviceId,
    required this.connected,
    this.reason,
  });

  String deviceId;

  bool connected;

  String? reason;

  List<Object?> _toList() {
    return <Object?>[deviceId, connected, reason];
  }

  Object encode() {
    return _toList();
  }

  static ConnectionEvent decode(Object result) {
    result as List<Object?>;
    return ConnectionEvent(
      deviceId: result[0]! as String,
      connected: result[1]! as bool,
      reason: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectionEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) &&
        _deepEquals(connected, other.connected) &&
        _deepEquals(reason, other.reason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConnectionEvent(deviceId: $deviceId, connected: $connected, reason: $reason)';
  }
}

class FrameEvent extends BleEvent {
  FrameEvent({
    required this.deviceId,
    required this.source,
    required this.frame,
  });

  String deviceId;

  Characteristic source;

  WireFrame frame;

  List<Object?> _toList() {
    return <Object?>[deviceId, source, frame];
  }

  Object encode() {
    return _toList();
  }

  static FrameEvent decode(Object result) {
    result as List<Object?>;
    return FrameEvent(
      deviceId: result[0]! as String,
      source: result[1]! as Characteristic,
      frame: result[2]! as WireFrame,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FrameEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) &&
        _deepEquals(source, other.source) &&
        _deepEquals(frame, other.frame);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FrameEvent(deviceId: $deviceId, source: $source, frame: $frame)';
  }
}

class CorruptedFrameEvent extends BleEvent {
  CorruptedFrameEvent({required this.deviceId, required this.reason});

  String deviceId;

  String reason;

  List<Object?> _toList() {
    return <Object?>[deviceId, reason];
  }

  Object encode() {
    return _toList();
  }

  static CorruptedFrameEvent decode(Object result) {
    result as List<Object?>;
    return CorruptedFrameEvent(
      deviceId: result[0]! as String,
      reason: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CorruptedFrameEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) &&
        _deepEquals(reason, other.reason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CorruptedFrameEvent(deviceId: $deviceId, reason: $reason)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AdapterState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PermissionState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is Characteristic) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is WireFrame) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is ScanResultEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ConnectionEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is FrameEvent) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is CorruptedFrameEvent) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AdapterState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PermissionState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : Characteristic.values[value];
      case 132:
        return WireFrame.decode(readValue(buffer)!);
      case 133:
        return ScanResultEvent.decode(readValue(buffer)!);
      case 134:
        return ConnectionEvent.decode(readValue(buffer)!);
      case 135:
        return FrameEvent.decode(readValue(buffer)!);
      case 136:
        return CorruptedFrameEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class BleHostApi {
  /// Constructor for [BleHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BleHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AdapterState> adapterState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.ble_bridge.BleHostApi.adapterState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AdapterState;
  }

  /// Su Android 12 e successivi chiede BLUETOOTH_SCAN e BLUETOOTH_CONNECT.
  Future<PermissionState> requestPermissions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.ble_bridge.BleHostApi.requestPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PermissionState;
  }

  /// I risultati arrivano come [ScanResultEvent], filtrati sul servizio
  /// della centralina.
  Future<void> startScan() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.ble_bridge.BleHostApi.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopScan() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.ble_bridge.BleHostApi.stopScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Completa quando i servizi sono stati scoperti e le notifiche abilitate:
  /// da lì in poi il canale è pronto.
  Future<void> connect(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.ble_bridge.BleHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> disconnect(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.ble_bridge.BleHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Legge la caratteristica delle informazioni.
  Future<WireFrame> readInfo(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.ble_bridge.BleHostApi.readInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WireFrame;
  }

  /// Codifica la trama nel C e la scrive con risposta sulla caratteristica dei
  /// comandi. Completa quando la centralina ha ricevuto i byte.
  Future<void> sendFrame(String deviceId, WireFrame frame) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.ble_bridge.BleHostApi.sendFrame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId, frame],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Returns a broadcast [Stream] of events from the `events` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<BleEvent> events({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel eventsChannel = EventChannel(
    'dev.flutter.pigeon.ble_bridge.BleEventsApi.events$instanceName',
    pigeonMethodCodec,
  );
  return eventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as BleEvent;
  });
}
