// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package it.mircozanzaro.ble_bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object BleApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class AdapterState(val raw: Int) {
  ON(0),
  OFF(1),
  UNAVAILABLE(2),
  UNAUTHORIZED(3);

  companion object {
    fun ofRaw(raw: Int): AdapterState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PermissionState(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  PERMANENTLY_DENIED(2);

  companion object {
    fun ofRaw(raw: Int): PermissionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** La caratteristica da cui è arrivata una trama. */
enum class Characteristic(val raw: Int) {
  RESPONSE(0),
  TELEMETRY(1);

  companion object {
    fun ofRaw(raw: Int): Characteristic? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Una trama già verificata dal C: tipo, sequenza e contenuto. CRC e versione
 * non attraversano il canale.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WireFrame (
  val type: Long,
  val seq: Long,
  val payload: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireFrame {
      val type = pigeonVar_list[0] as Long
      val seq = pigeonVar_list[1] as Long
      val payload = pigeonVar_list[2] as ByteArray
      return WireFrame(type, seq, payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      seq,
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WireFrame
    return BleApiPigeonUtils.deepEquals(this.type, other.type) && BleApiPigeonUtils.deepEquals(this.seq, other.seq) && BleApiPigeonUtils.deepEquals(this.payload, other.payload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.type)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.seq)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.payload)
    return result
  }
  override fun toString(): String {
    return "WireFrame(type=$type, seq=$seq, payload=${payload.contentToString()})"
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class BleEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class ScanResultEvent (
  val deviceId: String,
  val name: String? = null,
  val rssi: Long
) : BleEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanResultEvent {
      val deviceId = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val rssi = pigeonVar_list[2] as Long
      return ScanResultEvent(deviceId, name, rssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      name,
      rssi,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanResultEvent
    return BleApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && BleApiPigeonUtils.deepEquals(this.name, other.name) && BleApiPigeonUtils.deepEquals(this.rssi, other.rssi)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.name)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.rssi)
    return result
  }
  override fun toString(): String {
    return "ScanResultEvent(deviceId=$deviceId, name=$name, rssi=$rssi)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectionEvent (
  val deviceId: String,
  val connected: Boolean,
  val reason: String? = null
) : BleEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionEvent {
      val deviceId = pigeonVar_list[0] as String
      val connected = pigeonVar_list[1] as Boolean
      val reason = pigeonVar_list[2] as String?
      return ConnectionEvent(deviceId, connected, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      connected,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectionEvent
    return BleApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && BleApiPigeonUtils.deepEquals(this.connected, other.connected) && BleApiPigeonUtils.deepEquals(this.reason, other.reason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.connected)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.reason)
    return result
  }
  override fun toString(): String {
    return "ConnectionEvent(deviceId=$deviceId, connected=$connected, reason=$reason)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FrameEvent (
  val deviceId: String,
  val source: Characteristic,
  val frame: WireFrame
) : BleEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FrameEvent {
      val deviceId = pigeonVar_list[0] as String
      val source = pigeonVar_list[1] as Characteristic
      val frame = pigeonVar_list[2] as WireFrame
      return FrameEvent(deviceId, source, frame)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      source,
      frame,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FrameEvent
    return BleApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && BleApiPigeonUtils.deepEquals(this.source, other.source) && BleApiPigeonUtils.deepEquals(this.frame, other.frame)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.source)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.frame)
    return result
  }
  override fun toString(): String {
    return "FrameEvent(deviceId=$deviceId, source=$source, frame=$frame)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CorruptedFrameEvent (
  val deviceId: String,
  val reason: String
) : BleEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CorruptedFrameEvent {
      val deviceId = pigeonVar_list[0] as String
      val reason = pigeonVar_list[1] as String
      return CorruptedFrameEvent(deviceId, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CorruptedFrameEvent
    return BleApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && BleApiPigeonUtils.deepEquals(this.reason, other.reason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.reason)
    return result
  }
  override fun toString(): String {
    return "CorruptedFrameEvent(deviceId=$deviceId, reason=$reason)"
  }
}
private open class BleApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AdapterState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Characteristic.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireFrame.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanResultEvent.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionEvent.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FrameEvent.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CorruptedFrameEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AdapterState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is Characteristic -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is WireFrame -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ScanResultEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ConnectionEvent -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is FrameEvent -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CorruptedFrameEvent -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val BleApiPigeonMethodCodec = StandardMethodCodec(BleApiPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BleHostApi {
  fun adapterState(): AdapterState
  /** Su Android 12 e successivi chiede BLUETOOTH_SCAN e BLUETOOTH_CONNECT. */
  suspend fun requestPermissions(): PermissionState
  /**
   * I risultati arrivano come [ScanResultEvent], filtrati sul servizio
   * della centralina.
   */
  fun startScan()
  fun stopScan()
  /**
   * Completa quando i servizi sono stati scoperti e le notifiche abilitate:
   * da lì in poi il canale è pronto.
   */
  suspend fun connect(deviceId: String)
  fun disconnect(deviceId: String)
  /** Legge la caratteristica delle informazioni. */
  suspend fun readInfo(deviceId: String): WireFrame
  /**
   * Codifica la trama nel C e la scrive con risposta sulla caratteristica dei
   * comandi. Completa quando la centralina ha ricevuto i byte.
   */
  suspend fun sendFrame(deviceId: String, frame: WireFrame)

  companion object {
    /** The codec used by BleHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BleApiPigeonCodec()
    }
    /** Sets up an instance of `BleHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BleHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_bridge.BleHostApi.adapterState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.adapterState())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_bridge.BleHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestPermissions())
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_bridge.BleHostApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startScan()
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_bridge.BleHostApi.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScan()
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_bridge.BleHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.connect(deviceIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_bridge.BleHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.disconnect(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_bridge.BleHostApi.readInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.readInfo(deviceIdArg))
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_bridge.BleHostApi.sendFrame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val frameArg = args[1] as WireFrame
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.sendFrame(deviceIdArg, frameArg)
                listOf(null)
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class BleApiPigeonStreamHandler<T>(
    val wrapper: BleApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface BleApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class EventsStreamHandler : BleApiPigeonEventChannelWrapper<BleEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: EventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.ble_bridge.BleEventsApi.events"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = BleApiPigeonStreamHandler<BleEvent>(streamHandler)
      EventChannel(messenger, channelName, BleApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from BleApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<BleEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
